import fs from "node:fs/promises";
import path from "node:path";
import https from "node:https";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, "..");

const OUT_DIR = path.join(__dirname, "payload");
const OUT_FILE = path.join(OUT_DIR, "autofill_runtime.js");

const LOCAL_SOURCES = {
    obs: path.join(workspaceRoot, "autofill_obs.js"),
    bot: path.join(workspaceRoot, "autofill_bot.js")
};

const REMOTE_SOURCES = {
    obs: "https://raw.githubusercontent.com/MrKadyroff/AFM/refs/heads/main/autofill_obs.js",
    bot: "https://raw.githubusercontent.com/MrKadyroff/AFM/refs/heads/main/autofill_bot.js"
};

function readArg(name, fallback) {
    const prefix = `--${name}=`;
    const item = process.argv.find((a) => a.startsWith(prefix));
    if (!item) return fallback;
    return item.slice(prefix.length).trim() || fallback;
}

function stripUserscriptHeader(code) {
    return code.replace(/\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/m, "");
}

function download(url) {
    return new Promise((resolve, reject) => {
        https.get(url, (res) => {
            if (res.statusCode !== 200) { reject(new Error(`HTTP ${res.statusCode}`)); res.resume(); return; }
            let data = ""; res.setEncoding("utf8");
            res.on("data", (c) => data += c);
            res.on("end", () => resolve(data));
        }).on("error", reject);
    });
}

const source = readArg("source", "local").toLowerCase();
const variant = readArg("variant", "obs").toLowerCase();

if (!LOCAL_SOURCES[variant] || !REMOTE_SOURCES[variant]) {
    throw new Error(`Unknown variant: ${variant}. Expected one of: ${Object.keys(LOCAL_SOURCES).join(", ")}`);
}

let code = "";
if (source === "local") {
    const sourcePath = LOCAL_SOURCES[variant];
    console.log(`↓ Берем локальный payload: ${path.relative(workspaceRoot, sourcePath)}`);
    code = await fs.readFile(sourcePath, "utf8");
} else if (source === "remote") {
    const sourceUrl = REMOTE_SOURCES[variant];
    console.log(`↓ Скачиваем payload из GitHub: ${sourceUrl}`);
    code = await download(sourceUrl);
} else {
    throw new Error(`Unknown source: ${source}. Use local or remote.`);
}

const runtimeBody = stripUserscriptHeader(code).trimStart();
if (!runtimeBody) {
    throw new Error("Payload is empty after preprocessing.");
}

await fs.mkdir(OUT_DIR, { recursive: true });
await fs.writeFile(
    OUT_FILE,
    `// Generated by chrome-ext-afm/build.mjs\n// source=${source}; variant=${variant}\n\n${runtimeBody}\n`,
    "utf8"
);
console.log("✓ Обновлено:", path.relative(workspaceRoot, OUT_FILE));
