import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, "..");

const OUT_DIR = path.join(__dirname, "payload");
const OUT_FILE = path.join(OUT_DIR, "autofill_runtime.js");
const SOURCE_FILE = path.join(workspaceRoot, "autofill_obs.js");

function stripUserscriptHeader(code) {
    return code.replace(/\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/m, "");
}

console.log(`↓ Берем локальный payload: ${path.relative(workspaceRoot, SOURCE_FILE)}`);
const code = await fs.readFile(SOURCE_FILE, "utf8");

const runtimeBody = stripUserscriptHeader(code).trimStart();
if (!runtimeBody) {
    throw new Error("Payload is empty after preprocessing.");
}

await fs.mkdir(OUT_DIR, { recursive: true });
await fs.writeFile(
    OUT_FILE,
    `// Generated by chrome-ext-afm/build.mjs\n// source=local; variant=obs\n\n${runtimeBody}\n`,
    "utf8"
);
console.log("✓ Обновлено:", path.relative(workspaceRoot, OUT_FILE));
